  version: "3.8"
  services:
    server:
      build: ./server
      container_name: server_fastapi
      ports:
        - "5000:5000"
      depends_on:
        - mongo
      environment:
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_NAME: ${DB_NAME}
        DB_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        DB_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        DB_COLLECTIONS: ${DB_COLLECTIONS}
        JWT_SECRET: ${JWT_SECRET}
        JWT_ALGORITHM: ${JWT_ALGORITHM}
        UPLOAD_FOLDER: ${UPLOAD_FOLDER}
      hostname: api
      volumes:
        - ./server/data/upload_files:/code/data/upload_files/
    client:
      build: ./client
      container_name: client_react
      depends_on:
        - server
      ports:
        - "80:80"
      stdin_open: true
      tty: true
    mongo:
      image: mongo
      restart: always
      container_name: mongo_c
      volumes:
        - ./server/data/mongo_db_storage:/data/db
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
