  version: "3.8"
  services:
    server:
      build: ./server
      container_name: party_server
      ports:
        - "5000:5000"
      depends_on:
        - postgres_db
      environment:
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_NAME: ${DB_NAME}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD}
        JWT_SECRET: ${JWT_SECRET}
        JWT_ALGORITHM: ${JWT_ALGORITHM}
        UPLOAD_FOLDER: ${UPLOAD_FOLDER}
        API_SCHEMA: ${API_SCHEMA}
        API_HOST: ${API_HOST}
        API_PORT: ${API_PORT}
      hostname: api
      volumes:
        - upload_files:/code/server/data/upload_files/
        - logs:/code/server/data/logs/
    client:
      build: ./client
      container_name: party_client
      depends_on:
        - server
      ports:
        - "80:80"
      stdin_open: true
      tty: true
      environment:
        REACT_APP_SERVER_PORT: "5000"
    postgres_db:
      image: postgres:13
      container_name: postgres_db
      restart: unless-stopped
      environment:
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
    redis:
      image: redis:latest
      container_name: botRedis
      restart: always
      ports:
        - "6379:6379"
      command: redis-server --requirepass ${REDIS_PASSWORD}
      environment:
        - REDIS_PASSWORD=${REDIS_PASSWORD}
  volumes:
    postgres_data:
    upload_files:
    logs:
