version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    stream: ext://sys.stdout
    formatter: simple
  server-file:
    class: logging.FileHandler
    level: INFO
    filename: server/data/logs/server.log
    formatter: simple
  storage-cleaner-file:
    class: logging.FileHandler
    level: INFO
    filename: server/data/logs/storage_cleaner.log
    formatter: simple
  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: server/data/logs/uvicorn.log
    maxBytes: 10000000
    backupCount: 5
    delay: true
loggers:
  server:
    level: INFO
    handlers: [server-file]
    propagate: no
  storage_cleaner:
    level: INFO
    handlers: [console,  storage-cleaner-file]
    propagate: no
root:
  level: INFO
  handlers: [file_handler, console]