version: 1
handlers:
  file_handler:
    class: logging.FileHandler
    filename: logs/bot.log
    level: DEBUG
    formatter: simple
  console:
    class: logging.StreamHandler
    level: INFO
    stream: ext://sys.stdout
    formatter: simple
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
loggers:
  bot:
    level: INFO
    handlers: [file_handler, console]
    propagate: no
root:
  level: DEBUG
  handlers: [file_handler]
